[package]
name = "socialname-protocol"
description = "Versioned public API and event DTOs for SocialName"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[dev-dependencies]

[lints]
workspace = true
