[package]
name = "socialname-server"
description = "Axum and Tower modular-monolith server for SocialName"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-stream.workspace = true
axum.workspace = true
futures-util.workspace = true
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
socialname-protocol = { path = "../socialname-protocol" }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
